import { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import { useEffect } from 'react'
import useStore, { Shape } from '@/store'

const Home: NextPage = () => {
  const shapes = useStore((state) => state.shapes);
  const enterRoom = useStore((state) => state.liveblocks.enterRoom);
  const leaveRoom = useStore((state) => state.liveblocks.leaveRoom);
  const isLoading = useStore((state) => state.liveblocks.isStorageLoading);

  useEffect(() => {
    enterRoom("zustand-whiteboard");
    console.log("entered room maybe");
    return () => {
      leaveRoom("zustand-whiteboard");
    };
  }, [enterRoom, leaveRoom]);

  return (
    <>
      <Head>
        <title>PrompterSocial</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Prompter<span className="text-[hsl(280,100%,70%)]">Social</span>
          </h1>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {isLoading ? "Loading" : "Let us test Liveblocks"}
            </p>
            {!isLoading && (
              <div className="canvas">
                {Object.entries(shapes).map(([shapeId, shape]) => {
                  return <Rectangle key={shapeId} shape={shape} />;
                })}
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const Rectangle = ({ shape }: { shape: Shape }) => {
  return (
    <div
      className="rectangle"
      style={{
        transform: `translate(${shape.x}px, ${shape.y}px)`,
        backgroundColor: shape.fill ? shape.fill : "#CCC",
      }}
    ></div>
  );
};
